"""[ADD] settings table

Revision ID: 53c8de71b862
Revises: 04853ce6d5d4
Create Date: 2022-07-22 14:38:27.487691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c8de71b862'
down_revision = '04853ce6d5d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_can_comment', sa.Boolean(), nullable=False),
    sa.Column('users_can_register', sa.Boolean(), nullable=False),
    sa.Column('verify_email', sa.Boolean(), nullable=False),
    sa.Column('show_social_media_shares', sa.Boolean(), nullable=False),
    sa.Column('date_and_time_format', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
