"""[FIX] Rename field in Comment.

Revision ID: 5b859e49d85a
Revises: 75a9b0e5b99b
Create Date: 2022-07-20 23:11:06.482671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b859e49d85a'
down_revision = '75a9b0e5b99b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('comment', 'content')
    # ### end Alembic commands ###
