"""[FIX] Self ref in comments.

Revision ID: 75a9b0e5b99b
Revises: 46e79f6d3476
Create Date: 2022-07-20 22:45:36.829670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a9b0e5b99b'
down_revision = '46e79f6d3476'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
