"""[ADD] Add default settings & captcha option

Revision ID: f1a799f780cc
Revises: 53c8de71b862
Create Date: 2022-07-22 15:43:54.493544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a799f780cc'
down_revision = '53c8de71b862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('use_comment_captcha_for_anonymous', sa.Boolean(), nullable=False))
    op.add_column('settings', sa.Column('use_comment_captcha_for_registered', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'use_comment_captcha_for_registered')
    op.drop_column('settings', 'use_comment_captcha_for_anonymous')
    # ### end Alembic commands ###
